from collections.abc import Callable
from pathlib import Path

import pytest
from sqlmodel import Session

from kajet_turbo.db import Database
from kajet_turbo.embedding.cache import EmbeddingCacheRepository
from kajet_turbo.models import User
from kajet_turbo.repositories.active_workspace import ActiveWorkspaceRepository
from kajet_turbo.repositories.dangling_links import DanglingLinkRepository
from kajet_turbo.repositories.folder_meta import FolderMetaRepository
from kajet_turbo.repositories.jobs import JobRepository
from kajet_turbo.repositories.link_reconcile import LinkReconcileRepository
from kajet_turbo.repositories.notes import (
    NoteChunkRepository,
    NoteLinkRepository,
    NoteRepository,
    NoteTagRepository,
)
from kajet_turbo.repositories.workspace_meta import WorkspaceMetaRepository
from kajet_turbo.repositories.workspace_remote import WorkspaceRemoteRepository
from kajet_turbo.repositories.workspaces import WorkspaceRepository
from kajet_turbo.services.indexing import NoteIndexer
from kajet_turbo.services.notes import (
    NoteFolderService,
    NoteLinkService,
    NoteSearchService,
    NoteService,
    NoteTagService,
    NoteVersionService,
)
from kajet_turbo.services.targets import NoteTarget, WorkspaceTarget
from kajet_turbo.services.workspaces import WorkspaceService


def seed_user(database: Database, user_id: str) -> None:
    """Insert a User row with a fixed id — workspace_access/workspace_remotes/jobs FK to
    users.id, and several tests need a predictable id (e.g. "u1") rather than one
    generated by UserRepository.create. A no-op if the id already exists, so a file's own
    explicit seeding and an autouse fixture calling this for the same id don't collide."""
    with Session(database.engine) as session:
        if session.get(User, user_id) is not None:
            return
        session.add(
            User(
                id=user_id,
                email=f"{user_id}@test.com",
                password_hash="x",
                created_at="2026-01-01",
            )
        )
        session.commit()


def build_note_service(
    database: Database,
    indexer=None,
    link_validation_enabled=None,
    dangling_repo=None,
    query_resolver=None,
    build_embedder=None,
    query_cache=None,
    chunk_repo: NoteChunkRepository | None = None,
    async_build_embedder=None,
    reconcile_repo: LinkReconcileRepository | None = None,
    jobs: JobRepository | None = None,
) -> NoteService:
    """Construct a fully-wired NoteService from a Database for tests."""
    engine = database.engine
    crud_repo = NoteRepository(engine)
    link_repo = NoteLinkRepository(engine)
    tag_repo = NoteTagRepository(engine)
    if chunk_repo is None:
        chunk_repo = NoteChunkRepository(engine)
    if jobs is None:
        jobs = JobRepository(engine)

    tag_service = NoteTagService(crud_repo, tag_repo)
    link_service = NoteLinkService(
        crud_repo, link_repo, dangling_repo, link_validation_enabled, jobs
    )
    search_service = NoteSearchService(
        chunk_repo,
        query_resolver,
        build_embedder,
        query_cache,
        crud_repo,
        tag_repo,
        async_build_embedder=async_build_embedder,
    )
    version_service = NoteVersionService(crud_repo)
    folder_service = NoteFolderService(crud_repo, link_service, reconcile_repo=reconcile_repo)

    return NoteService(
        crud_repo,
        link_repo,
        tag_repo,
        chunk_repo,
        tag_service,
        link_service,
        search_service,
        version_service,
        folder_service,
        indexer=indexer,
        reconcile_repo=reconcile_repo,
    )


def build_workspace_service(database: Database) -> WorkspaceService:
    """Construct a fully-wired WorkspaceService from a Database for tests."""
    engine = database.engine
    jobs = JobRepository(engine)
    reconcile_repo = LinkReconcileRepository(engine, jobs)
    return WorkspaceService(
        WorkspaceRepository(engine),
        NoteRepository(engine),
        WorkspaceMetaRepository(engine),
        build_note_service(database, reconcile_repo=reconcile_repo, jobs=jobs),
        DanglingLinkRepository(engine),
        FolderMetaRepository(engine),
        WorkspaceRemoteRepository(engine),
        ActiveWorkspaceRepository(engine),
        jobs,
        reconcile_repo=reconcile_repo,
    )


@pytest.fixture
def workspace(git_workspace_factory: Callable[[str], Path]) -> Path:
    return git_workspace_factory("workspace")


@pytest.fixture
def service(database: Database) -> NoteService:
    chunk_repo = NoteChunkRepository(database.engine)
    indexer = NoteIndexer(
        chunk_repo,
        EmbeddingCacheRepository(database.engine),
        resolve_backend=lambda owner_id: None,  # FTS-only in tests (no network)
        jobs=JobRepository(database.engine),
    )
    return build_note_service(database, indexer=indexer)


def workspace_target(owner_id: str, name: str, path) -> WorkspaceTarget:
    """Build a WorkspaceTarget by hand for tests that call NoteService entry points
    directly, bypassing the real TargetResolver (already covered by test_targets.py)."""
    return WorkspaceTarget(owner_id=owner_id, name=name, path=Path(path))


def note_target(owner_id: str, name: str, path, note_id: str) -> NoteTarget:
    return NoteTarget(note_id=note_id, workspace=workspace_target(owner_id, name, path))
