from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

import pytest
from sqlmodel import Session

from kajet_turbo.db import Database
from kajet_turbo.embedding.cache import EmbeddingCacheRepository
from kajet_turbo.models import User
from kajet_turbo.repositories.dangling_links import DanglingLinkRepository
from kajet_turbo.repositories.folder_meta import FolderMetaRepository
from kajet_turbo.repositories.jobs import JobRepository
from kajet_turbo.repositories.link_reconcile import LinkReconcileRepository
from kajet_turbo.repositories.notes import (
    NoteChunkRepository,
    NoteLinkRepository,
    NoteRepository,
    NoteTagRepository,
)
from kajet_turbo.repositories.workspace_meta import WorkspaceMetaRepository
from kajet_turbo.repositories.workspace_remote import WorkspaceRemoteRepository
from kajet_turbo.repositories.workspaces import WorkspaceRepository
from kajet_turbo.services.indexing import NoteIndexer
from kajet_turbo.services.notes import (
    NoteFolderService,
    NoteLinkService,
    NoteReadService,
    NoteSearchService,
    NoteService,
    NoteTagService,
    NoteTemporalService,
    NoteVersionService,
)
from kajet_turbo.services.targets import NoteTarget, WorkspaceTarget
from kajet_turbo.services.workspaces import WorkspaceService


def seed_user(database: Database, user_id: str) -> None:
    """Insert a User row with a fixed id — workspace_access/workspace_remotes/jobs FK to
    users.id, and several tests need a predictable id (e.g. "u1") rather than one
    generated by UserRepository.create. A no-op if the id already exists, so a file's own
    explicit seeding and an autouse fixture calling this for the same id don't collide."""
    with Session(database.engine) as session:
        if session.get(User, user_id) is not None:
            return
        session.add(
            User(
                id=user_id,
                email=f"{user_id}@test.com",
                password_hash="x",
                created_at="2026-01-01",
            )
        )
        session.commit()


@dataclass(frozen=True)
class NoteWiring:
    """The concrete note service graph, with the boundaries a test may need as its subject.

    A test that drives writes through ``NoteService`` but asserts on the link graph takes
    ``link_service`` from here rather than from a second, separately built one: the builder
    hands both services the same ``NoteRepository``, so patching ``service._crud_repo`` —
    to count workspace snapshots, say — still intercepts the link service's reads."""

    service: NoteService
    link_service: NoteLinkService


def build_note_wiring(
    database: Database,
    indexer=None,
    link_validation_enabled=None,
    dangling_repo=None,
    chunk_repo: NoteChunkRepository | None = None,
    reconcile_repo: LinkReconcileRepository | None = None,
    jobs: JobRepository | None = None,
    link_service: NoteLinkService | None = None,
) -> NoteWiring:
    """Construct a fully-wired NoteService from a Database for tests, plus the peer
    boundaries a test may need to address directly."""
    engine = database.engine
    crud_repo = NoteRepository(engine)
    link_repo = NoteLinkRepository(engine)
    tag_repo = NoteTagRepository(engine)
    if chunk_repo is None:
        chunk_repo = NoteChunkRepository(engine)
    if jobs is None:
        jobs = JobRepository(engine)

    tag_service = NoteTagService(crud_repo, tag_repo, indexer)
    if link_service is None:
        link_service = NoteLinkService(
            crud_repo, link_repo, tag_repo, dangling_repo, link_validation_enabled, jobs
        )
    version_service = NoteVersionService(crud_repo)
    folder_service = NoteFolderService(crud_repo, link_service, reconcile_repo=reconcile_repo)

    return NoteWiring(
        service=NoteService(
            crud_repo,
            link_repo,
            tag_repo,
            chunk_repo,
            tag_service,
            link_service,
            version_service,
            folder_service,
            indexer=indexer,
            reconcile_repo=reconcile_repo,
        ),
        link_service=link_service,
    )


def build_note_service(database: Database, **kwargs) -> NoteService:
    """The note writer alone — for callers that need no other boundary."""
    return build_note_wiring(database, **kwargs).service


def build_note_search_service(
    database: Database,
    query_resolver=None,
    build_embedder=None,
    query_cache=None,
    chunk_repo: NoteChunkRepository | None = None,
    async_build_embedder=None,
) -> NoteSearchService:
    """Construct a NoteSearchService reading the same Database as build_note_service.

    Fresh repo instances on the same engine — stateless, so they see everything a
    NoteService built against the same Database has already written."""
    engine = database.engine
    crud_repo = NoteRepository(engine)
    tag_repo = NoteTagRepository(engine)
    if chunk_repo is None:
        chunk_repo = NoteChunkRepository(engine)
    return NoteSearchService(
        chunk_repo,
        query_resolver,
        build_embedder,
        query_cache,
        crud_repo,
        tag_repo,
        async_build_embedder=async_build_embedder,
    )


def build_note_read_service(database: Database, indexer=None) -> NoteReadService:
    """Construct a NoteReadService reading the same Database as build_note_service.

    NoteLinkService.for_workspace takes a fresh DB snapshot on every call (no
    per-instance caching), so a separately-constructed NoteLinkService here sees
    everything a NoteService built against the same Database has already written."""
    engine = database.engine
    crud_repo = NoteRepository(engine)
    tag_repo = NoteTagRepository(engine)
    link_service = NoteLinkService(
        crud_repo, NoteLinkRepository(engine), tag_repo, None, None, JobRepository(engine)
    )
    return NoteReadService(crud_repo, tag_repo, link_service, indexer=indexer)


def build_note_reconcile_service(
    database: Database,
    link_service: NoteLinkService | None = None,
    dangling_repo: DanglingLinkRepository | None = None,
    link_validation_enabled=None,
    jobs: JobRepository | None = None,
    chunk_repo: NoteChunkRepository | None = None,
    indexer=None,
    reconcile_repo: LinkReconcileRepository | None = None,
):
    """Construct a NoteReconcileService from a Database for tests, without building a
    full NoteService — the point of #225's split."""
    from kajet_turbo.services.notes import NoteReconcileService

    engine = database.engine
    crud_repo = NoteRepository(engine)
    link_repo = NoteLinkRepository(engine)
    tag_repo = NoteTagRepository(engine)
    if chunk_repo is None:
        chunk_repo = NoteChunkRepository(engine)
    if jobs is None:
        jobs = JobRepository(engine)
    if link_service is None:
        link_service = NoteLinkService(
            crud_repo, link_repo, tag_repo, dangling_repo, link_validation_enabled, jobs
        )
    return NoteReconcileService(
        crud_repo,
        link_repo,
        tag_repo,
        chunk_repo,
        link_service,
        indexer=indexer,
        reconcile_repo=reconcile_repo,
    )


def build_workspace_service(database: Database) -> WorkspaceService:
    """Construct a fully-wired WorkspaceService from a Database for tests."""
    engine = database.engine
    jobs = JobRepository(engine)
    reconcile_repo = LinkReconcileRepository(engine, jobs)
    return WorkspaceService(
        WorkspaceRepository(engine),
        NoteRepository(engine),
        WorkspaceMetaRepository(engine),
        build_note_reconcile_service(database, jobs=jobs),
        DanglingLinkRepository(engine),
        FolderMetaRepository(engine),
        WorkspaceRemoteRepository(engine),
        jobs,
        reconcile_repo=reconcile_repo,
    )


@pytest.fixture
def workspace(git_workspace_factory: Callable[[str], Path]) -> Path:
    return git_workspace_factory("workspace")


@pytest.fixture
def service(database: Database) -> NoteService:
    chunk_repo = NoteChunkRepository(database.engine)
    indexer = NoteIndexer(
        chunk_repo,
        EmbeddingCacheRepository(database.engine),
        resolve_backend=lambda owner_id: None,  # FTS-only in tests (no network)
        jobs=JobRepository(database.engine),
    )
    return build_note_service(database, indexer=indexer)


@pytest.fixture
def reconcile_service(service: NoteService):
    """A NoteReconcileService sharing every repo/collaborator instance the `service`
    fixture already holds (see build_note_reconcile_service_from) — reconcile_paths/
    reindex on this fixture and save()/update() on `service` operate on the same DB
    state, same as production wiring."""
    from tests.services.helpers import build_note_reconcile_service_from

    return build_note_reconcile_service_from(service)


@pytest.fixture
def tag_service(service: NoteService) -> NoteTagService:
    """The concrete tag boundary paired with the note writer in service tests."""
    return service._tag_service


@pytest.fixture
def temporal_service(service: NoteService) -> NoteTemporalService:
    """Shares `service`'s NoteRepository instance, not a fresh one, so a test that
    patches a method on `service._crud_repo` also affects backfill calls made here."""
    return NoteTemporalService(service._crud_repo)


@pytest.fixture
def read_service(database: Database) -> NoteReadService:
    return build_note_read_service(database)


@pytest.fixture
def search_service(database: Database) -> NoteSearchService:
    return build_note_search_service(database)


@pytest.fixture
def link_service(database: Database) -> NoteLinkService:
    """Direct link-service boundary for tests that inspect the link graph."""
    engine = database.engine
    return NoteLinkService(
        NoteRepository(engine),
        NoteLinkRepository(engine),
        NoteTagRepository(engine),
        None,
        None,
        JobRepository(engine),
    )


def workspace_target(owner_id: str, name: str, path) -> WorkspaceTarget:
    """Build a WorkspaceTarget by hand for tests that call NoteService entry points
    directly, bypassing the real TargetResolver (already covered by test_targets.py)."""
    return WorkspaceTarget(owner_id=owner_id, name=name, path=Path(path))


def note_target(owner_id: str, name: str, path, note_id: str) -> NoteTarget:
    return NoteTarget(note_id=note_id, workspace=workspace_target(owner_id, name, path))
