/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Kajet Turbo API
 * OpenAPI spec version: 0.1.0
 */
export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type ApiPendingInfoApiPendingGetParams = {
id: string;
};

export type apiLoginApiLoginPostResponse200 = {
  data: unknown
  status: 200
}

export type apiLoginApiLoginPostResponseSuccess = (apiLoginApiLoginPostResponse200) & {
  headers: Headers;
};
;

export type apiLoginApiLoginPostResponse = (apiLoginApiLoginPostResponseSuccess)

export const getApiLoginApiLoginPostUrl = () => {




  return `/api/login`
}

/**
 * @summary Api Login
 */
export const apiLoginApiLoginPost = async ( options?: RequestInit): Promise<apiLoginApiLoginPostResponse> => {

  const res = await fetch(getApiLoginApiLoginPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiLoginApiLoginPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiLoginApiLoginPostResponse
}



export type apiSessionGetApiSessionGetResponse200 = {
  data: unknown
  status: 200
}

export type apiSessionGetApiSessionGetResponseSuccess = (apiSessionGetApiSessionGetResponse200) & {
  headers: Headers;
};
;

export type apiSessionGetApiSessionGetResponse = (apiSessionGetApiSessionGetResponseSuccess)

export const getApiSessionGetApiSessionGetUrl = () => {




  return `/api/session`
}

/**
 * @summary Api Session Get
 */
export const apiSessionGetApiSessionGet = async ( options?: RequestInit): Promise<apiSessionGetApiSessionGetResponse> => {

  const res = await fetch(getApiSessionGetApiSessionGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiSessionGetApiSessionGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiSessionGetApiSessionGetResponse
}



export type apiSessionDeleteApiSessionDeleteResponse200 = {
  data: unknown
  status: 200
}

export type apiSessionDeleteApiSessionDeleteResponseSuccess = (apiSessionDeleteApiSessionDeleteResponse200) & {
  headers: Headers;
};
;

export type apiSessionDeleteApiSessionDeleteResponse = (apiSessionDeleteApiSessionDeleteResponseSuccess)

export const getApiSessionDeleteApiSessionDeleteUrl = () => {




  return `/api/session`
}

/**
 * @summary Api Session Delete
 */
export const apiSessionDeleteApiSessionDelete = async ( options?: RequestInit): Promise<apiSessionDeleteApiSessionDeleteResponse> => {

  const res = await fetch(getApiSessionDeleteApiSessionDeleteUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiSessionDeleteApiSessionDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiSessionDeleteApiSessionDeleteResponse
}



export type apiConsentApiConsentPostResponse200 = {
  data: unknown
  status: 200
}

export type apiConsentApiConsentPostResponseSuccess = (apiConsentApiConsentPostResponse200) & {
  headers: Headers;
};
;

export type apiConsentApiConsentPostResponse = (apiConsentApiConsentPostResponseSuccess)

export const getApiConsentApiConsentPostUrl = () => {




  return `/api/consent`
}

/**
 * @summary Api Consent
 */
export const apiConsentApiConsentPost = async ( options?: RequestInit): Promise<apiConsentApiConsentPostResponse> => {

  const res = await fetch(getApiConsentApiConsentPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiConsentApiConsentPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiConsentApiConsentPostResponse
}



export type apiPendingInfoApiPendingGetResponse200 = {
  data: unknown
  status: 200
}

export type apiPendingInfoApiPendingGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiPendingInfoApiPendingGetResponseSuccess = (apiPendingInfoApiPendingGetResponse200) & {
  headers: Headers;
};
export type apiPendingInfoApiPendingGetResponseError = (apiPendingInfoApiPendingGetResponse422) & {
  headers: Headers;
};

export type apiPendingInfoApiPendingGetResponse = (apiPendingInfoApiPendingGetResponseSuccess | apiPendingInfoApiPendingGetResponseError)

export const getApiPendingInfoApiPendingGetUrl = (params: ApiPendingInfoApiPendingGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pending?${stringifiedParams}` : `/api/pending`
}

/**
 * @summary Api Pending Info
 */
export const apiPendingInfoApiPendingGet = async (params: ApiPendingInfoApiPendingGetParams, options?: RequestInit): Promise<apiPendingInfoApiPendingGetResponse> => {

  const res = await fetch(getApiPendingInfoApiPendingGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiPendingInfoApiPendingGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiPendingInfoApiPendingGetResponse
}



export type apiListWorkspacesApiWorkspacesGetResponse200 = {
  data: unknown
  status: 200
}

export type apiListWorkspacesApiWorkspacesGetResponseSuccess = (apiListWorkspacesApiWorkspacesGetResponse200) & {
  headers: Headers;
};
;

export type apiListWorkspacesApiWorkspacesGetResponse = (apiListWorkspacesApiWorkspacesGetResponseSuccess)

export const getApiListWorkspacesApiWorkspacesGetUrl = () => {




  return `/api/workspaces`
}

/**
 * @summary Api List Workspaces
 */
export const apiListWorkspacesApiWorkspacesGet = async ( options?: RequestInit): Promise<apiListWorkspacesApiWorkspacesGetResponse> => {

  const res = await fetch(getApiListWorkspacesApiWorkspacesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiListWorkspacesApiWorkspacesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiListWorkspacesApiWorkspacesGetResponse
}



export type apiCreateWorkspaceApiWorkspacesPostResponse200 = {
  data: unknown
  status: 200
}

export type apiCreateWorkspaceApiWorkspacesPostResponseSuccess = (apiCreateWorkspaceApiWorkspacesPostResponse200) & {
  headers: Headers;
};
;

export type apiCreateWorkspaceApiWorkspacesPostResponse = (apiCreateWorkspaceApiWorkspacesPostResponseSuccess)

export const getApiCreateWorkspaceApiWorkspacesPostUrl = () => {




  return `/api/workspaces`
}

/**
 * @summary Api Create Workspace
 */
export const apiCreateWorkspaceApiWorkspacesPost = async ( options?: RequestInit): Promise<apiCreateWorkspaceApiWorkspacesPostResponse> => {

  const res = await fetch(getApiCreateWorkspaceApiWorkspacesPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiCreateWorkspaceApiWorkspacesPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiCreateWorkspaceApiWorkspacesPostResponse
}



export type apiListNotesApiWorkspacesNameNotesGetResponse200 = {
  data: unknown
  status: 200
}

export type apiListNotesApiWorkspacesNameNotesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiListNotesApiWorkspacesNameNotesGetResponseSuccess = (apiListNotesApiWorkspacesNameNotesGetResponse200) & {
  headers: Headers;
};
export type apiListNotesApiWorkspacesNameNotesGetResponseError = (apiListNotesApiWorkspacesNameNotesGetResponse422) & {
  headers: Headers;
};

export type apiListNotesApiWorkspacesNameNotesGetResponse = (apiListNotesApiWorkspacesNameNotesGetResponseSuccess | apiListNotesApiWorkspacesNameNotesGetResponseError)

export const getApiListNotesApiWorkspacesNameNotesGetUrl = (name: string,) => {




  return `/api/workspaces/${name}/notes`
}

/**
 * @summary Api List Notes
 */
export const apiListNotesApiWorkspacesNameNotesGet = async (name: string, options?: RequestInit): Promise<apiListNotesApiWorkspacesNameNotesGetResponse> => {

  const res = await fetch(getApiListNotesApiWorkspacesNameNotesGetUrl(name),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiListNotesApiWorkspacesNameNotesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiListNotesApiWorkspacesNameNotesGetResponse
}



export type apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse200 = {
  data: unknown
  status: 200
}

export type apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponseSuccess = (apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse200) & {
  headers: Headers;
};
export type apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponseError = (apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse422) & {
  headers: Headers;
};

export type apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse = (apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponseSuccess | apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponseError)

export const getApiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetUrl = (name: string,
    noteId: string,) => {




  return `/api/workspaces/${name}/notes/${noteId}/html`
}

/**
 * @summary Api Get Note Html
 */
export const apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGet = async (name: string,
    noteId: string, options?: RequestInit): Promise<apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse> => {

  const res = await fetch(getApiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetUrl(name,noteId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse
}



export type apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse200 = {
  data: unknown
  status: 200
}

export type apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponseSuccess = (apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse200) & {
  headers: Headers;
};
export type apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponseError = (apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse422) & {
  headers: Headers;
};

export type apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse = (apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponseSuccess | apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponseError)

export const getApiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetUrl = (name: string,
    noteId: string,) => {




  return `/api/workspaces/${name}/notes/${noteId}/markdown`
}

/**
 * @summary Api Get Note Markdown
 */
export const apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGet = async (name: string,
    noteId: string, options?: RequestInit): Promise<apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse> => {

  const res = await fetch(getApiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetUrl(name,noteId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse
}
