/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Kajet Turbo API
 * OpenAPI spec version: 0.1.0
 */
export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LsEntry {
  note_id: string;
  title: string;
  size_bytes: number;
  updated_at: string;
}

export interface LsResponse {
  folders: string[];
  entries: LsEntry[];
}

export interface NoteHistoryEntry {
  sha: string;
  message: string;
  timestamp: number;
}

export interface NoteHistoryResponse {
  entries: NoteHistoryEntry[];
}

export interface NoteHtmlResponse {
  note_id: string;
  title: string;
  folder: string;
  tags: string[];
  created_at: string;
  updated_at: string;
  content_html: string;
}

export interface NoteItem {
  note_id: string;
  workspace: string;
  owner_id: string;
  title: string;
  folder: string;
  tags: string[];
  created_at: string;
  updated_at: string;
  size_bytes: number;
}

export interface NoteMarkdownResponse {
  note_id: string;
  title: string;
  folder: string;
  tags: string[];
  created_at: string;
  updated_at: string;
  content: string;
}

export interface NotesListResponse {
  notes: NoteItem[];
}

export interface WorkspaceInfo {
  name: string;
  file_count: number;
  last_commit_at: number | null;
}

export interface WorkspacesListResponse {
  workspaces: WorkspaceInfo[];
}

export type ApiPendingInfoApiPendingGetParams = {
id: string;
};

export type ApiListNotesApiWorkspacesNameNotesGetParams = {
folder?: string | null;
};

export type ApiLsApiWorkspacesNameLsGetParams = {
path?: string;
recursive?: boolean;
};

export type apiLoginApiLoginPostResponse200 = {
  data: unknown
  status: 200
}

export type apiLoginApiLoginPostResponseSuccess = (apiLoginApiLoginPostResponse200) & {
  headers: Headers;
};
;

export type apiLoginApiLoginPostResponse = (apiLoginApiLoginPostResponseSuccess)

export const getApiLoginApiLoginPostUrl = () => {




  return `/api/login`
}

/**
 * @summary Api Login
 */
export const apiLoginApiLoginPost = async ( options?: RequestInit): Promise<apiLoginApiLoginPostResponse> => {

  const res = await fetch(getApiLoginApiLoginPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiLoginApiLoginPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiLoginApiLoginPostResponse
}



export type apiSessionGetApiSessionGetResponse200 = {
  data: unknown
  status: 200
}

export type apiSessionGetApiSessionGetResponseSuccess = (apiSessionGetApiSessionGetResponse200) & {
  headers: Headers;
};
;

export type apiSessionGetApiSessionGetResponse = (apiSessionGetApiSessionGetResponseSuccess)

export const getApiSessionGetApiSessionGetUrl = () => {




  return `/api/session`
}

/**
 * @summary Api Session Get
 */
export const apiSessionGetApiSessionGet = async ( options?: RequestInit): Promise<apiSessionGetApiSessionGetResponse> => {

  const res = await fetch(getApiSessionGetApiSessionGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiSessionGetApiSessionGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiSessionGetApiSessionGetResponse
}



export type apiSessionDeleteApiSessionDeleteResponse200 = {
  data: unknown
  status: 200
}

export type apiSessionDeleteApiSessionDeleteResponseSuccess = (apiSessionDeleteApiSessionDeleteResponse200) & {
  headers: Headers;
};
;

export type apiSessionDeleteApiSessionDeleteResponse = (apiSessionDeleteApiSessionDeleteResponseSuccess)

export const getApiSessionDeleteApiSessionDeleteUrl = () => {




  return `/api/session`
}

/**
 * @summary Api Session Delete
 */
export const apiSessionDeleteApiSessionDelete = async ( options?: RequestInit): Promise<apiSessionDeleteApiSessionDeleteResponse> => {

  const res = await fetch(getApiSessionDeleteApiSessionDeleteUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiSessionDeleteApiSessionDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiSessionDeleteApiSessionDeleteResponse
}



export type apiConsentApiConsentPostResponse200 = {
  data: unknown
  status: 200
}

export type apiConsentApiConsentPostResponseSuccess = (apiConsentApiConsentPostResponse200) & {
  headers: Headers;
};
;

export type apiConsentApiConsentPostResponse = (apiConsentApiConsentPostResponseSuccess)

export const getApiConsentApiConsentPostUrl = () => {




  return `/api/consent`
}

/**
 * @summary Api Consent
 */
export const apiConsentApiConsentPost = async ( options?: RequestInit): Promise<apiConsentApiConsentPostResponse> => {

  const res = await fetch(getApiConsentApiConsentPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiConsentApiConsentPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiConsentApiConsentPostResponse
}



export type apiPendingInfoApiPendingGetResponse200 = {
  data: unknown
  status: 200
}

export type apiPendingInfoApiPendingGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiPendingInfoApiPendingGetResponseSuccess = (apiPendingInfoApiPendingGetResponse200) & {
  headers: Headers;
};
export type apiPendingInfoApiPendingGetResponseError = (apiPendingInfoApiPendingGetResponse422) & {
  headers: Headers;
};

export type apiPendingInfoApiPendingGetResponse = (apiPendingInfoApiPendingGetResponseSuccess | apiPendingInfoApiPendingGetResponseError)

export const getApiPendingInfoApiPendingGetUrl = (params: ApiPendingInfoApiPendingGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pending?${stringifiedParams}` : `/api/pending`
}

/**
 * @summary Api Pending Info
 */
export const apiPendingInfoApiPendingGet = async (params: ApiPendingInfoApiPendingGetParams, options?: RequestInit): Promise<apiPendingInfoApiPendingGetResponse> => {

  const res = await fetch(getApiPendingInfoApiPendingGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiPendingInfoApiPendingGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiPendingInfoApiPendingGetResponse
}



export type apiListWorkspacesApiWorkspacesGetResponse200 = {
  data: WorkspacesListResponse
  status: 200
}

export type apiListWorkspacesApiWorkspacesGetResponseSuccess = (apiListWorkspacesApiWorkspacesGetResponse200) & {
  headers: Headers;
};
;

export type apiListWorkspacesApiWorkspacesGetResponse = (apiListWorkspacesApiWorkspacesGetResponseSuccess)

export const getApiListWorkspacesApiWorkspacesGetUrl = () => {




  return `/api/workspaces`
}

/**
 * @summary Api List Workspaces
 */
export const apiListWorkspacesApiWorkspacesGet = async ( options?: RequestInit): Promise<apiListWorkspacesApiWorkspacesGetResponse> => {

  const res = await fetch(getApiListWorkspacesApiWorkspacesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiListWorkspacesApiWorkspacesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiListWorkspacesApiWorkspacesGetResponse
}



export type apiCreateWorkspaceApiWorkspacesPostResponse200 = {
  data: unknown
  status: 200
}

export type apiCreateWorkspaceApiWorkspacesPostResponseSuccess = (apiCreateWorkspaceApiWorkspacesPostResponse200) & {
  headers: Headers;
};
;

export type apiCreateWorkspaceApiWorkspacesPostResponse = (apiCreateWorkspaceApiWorkspacesPostResponseSuccess)

export const getApiCreateWorkspaceApiWorkspacesPostUrl = () => {




  return `/api/workspaces`
}

/**
 * @summary Api Create Workspace
 */
export const apiCreateWorkspaceApiWorkspacesPost = async ( options?: RequestInit): Promise<apiCreateWorkspaceApiWorkspacesPostResponse> => {

  const res = await fetch(getApiCreateWorkspaceApiWorkspacesPostUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiCreateWorkspaceApiWorkspacesPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiCreateWorkspaceApiWorkspacesPostResponse
}



export type apiListNotesApiWorkspacesNameNotesGetResponse200 = {
  data: NotesListResponse
  status: 200
}

export type apiListNotesApiWorkspacesNameNotesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiListNotesApiWorkspacesNameNotesGetResponseSuccess = (apiListNotesApiWorkspacesNameNotesGetResponse200) & {
  headers: Headers;
};
export type apiListNotesApiWorkspacesNameNotesGetResponseError = (apiListNotesApiWorkspacesNameNotesGetResponse422) & {
  headers: Headers;
};

export type apiListNotesApiWorkspacesNameNotesGetResponse = (apiListNotesApiWorkspacesNameNotesGetResponseSuccess | apiListNotesApiWorkspacesNameNotesGetResponseError)

export const getApiListNotesApiWorkspacesNameNotesGetUrl = (name: string,
    params?: ApiListNotesApiWorkspacesNameNotesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/workspaces/${name}/notes?${stringifiedParams}` : `/api/workspaces/${name}/notes`
}

/**
 * @summary Api List Notes
 */
export const apiListNotesApiWorkspacesNameNotesGet = async (name: string,
    params?: ApiListNotesApiWorkspacesNameNotesGetParams, options?: RequestInit): Promise<apiListNotesApiWorkspacesNameNotesGetResponse> => {

  const res = await fetch(getApiListNotesApiWorkspacesNameNotesGetUrl(name,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiListNotesApiWorkspacesNameNotesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiListNotesApiWorkspacesNameNotesGetResponse
}



export type apiLsApiWorkspacesNameLsGetResponse200 = {
  data: LsResponse
  status: 200
}

export type apiLsApiWorkspacesNameLsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiLsApiWorkspacesNameLsGetResponseSuccess = (apiLsApiWorkspacesNameLsGetResponse200) & {
  headers: Headers;
};
export type apiLsApiWorkspacesNameLsGetResponseError = (apiLsApiWorkspacesNameLsGetResponse422) & {
  headers: Headers;
};

export type apiLsApiWorkspacesNameLsGetResponse = (apiLsApiWorkspacesNameLsGetResponseSuccess | apiLsApiWorkspacesNameLsGetResponseError)

export const getApiLsApiWorkspacesNameLsGetUrl = (name: string,
    params?: ApiLsApiWorkspacesNameLsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/workspaces/${name}/ls?${stringifiedParams}` : `/api/workspaces/${name}/ls`
}

/**
 * @summary Api Ls
 */
export const apiLsApiWorkspacesNameLsGet = async (name: string,
    params?: ApiLsApiWorkspacesNameLsGetParams, options?: RequestInit): Promise<apiLsApiWorkspacesNameLsGetResponse> => {

  const res = await fetch(getApiLsApiWorkspacesNameLsGetUrl(name,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiLsApiWorkspacesNameLsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiLsApiWorkspacesNameLsGetResponse
}



export type apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse200 = {
  data: NoteHtmlResponse
  status: 200
}

export type apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponseSuccess = (apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse200) & {
  headers: Headers;
};
export type apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponseError = (apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse422) & {
  headers: Headers;
};

export type apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse = (apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponseSuccess | apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponseError)

export const getApiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetUrl = (name: string,
    noteId: string,) => {




  return `/api/workspaces/${name}/notes/${noteId}/html`
}

/**
 * @summary Api Get Note Html
 */
export const apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGet = async (name: string,
    noteId: string, options?: RequestInit): Promise<apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse> => {

  const res = await fetch(getApiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetUrl(name,noteId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiGetNoteHtmlApiWorkspacesNameNotesNoteIdHtmlGetResponse
}



export type apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse200 = {
  data: NoteMarkdownResponse
  status: 200
}

export type apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponseSuccess = (apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse200) & {
  headers: Headers;
};
export type apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponseError = (apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse422) & {
  headers: Headers;
};

export type apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse = (apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponseSuccess | apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponseError)

export const getApiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetUrl = (name: string,
    noteId: string,) => {




  return `/api/workspaces/${name}/notes/${noteId}/markdown`
}

/**
 * @summary Api Get Note Markdown
 */
export const apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGet = async (name: string,
    noteId: string, options?: RequestInit): Promise<apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse> => {

  const res = await fetch(getApiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetUrl(name,noteId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiGetNoteMarkdownApiWorkspacesNameNotesNoteIdMarkdownGetResponse
}



export type apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponse200 = {
  data: NoteHistoryResponse
  status: 200
}

export type apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponseSuccess = (apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponse200) & {
  headers: Headers;
};
export type apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponseError = (apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponse422) & {
  headers: Headers;
};

export type apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponse = (apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponseSuccess | apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponseError)

export const getApiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetUrl = (name: string,
    noteId: string,) => {




  return `/api/workspaces/${name}/notes/${noteId}/history`
}

/**
 * @summary Api Note History
 */
export const apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGet = async (name: string,
    noteId: string, options?: RequestInit): Promise<apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponse> => {

  const res = await fetch(getApiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetUrl(name,noteId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiNoteHistoryApiWorkspacesNameNotesNoteIdHistoryGetResponse
}



export type apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponse200 = {
  data: NoteHtmlResponse
  status: 200
}

export type apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponseSuccess = (apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponse200) & {
  headers: Headers;
};
export type apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponseError = (apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponse422) & {
  headers: Headers;
};

export type apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponse = (apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponseSuccess | apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponseError)

export const getApiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetUrl = (name: string,
    noteId: string,
    sha: string,) => {




  return `/api/workspaces/${name}/notes/${noteId}/history/${sha}`
}

/**
 * @summary Api Note Version
 */
export const apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGet = async (name: string,
    noteId: string,
    sha: string, options?: RequestInit): Promise<apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponse> => {

  const res = await fetch(getApiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetUrl(name,noteId,sha),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaGetResponse
}



export type apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponse200 = {
  data: unknown
  status: 200
}

export type apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponseSuccess = (apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponse200) & {
  headers: Headers;
};
export type apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponseError = (apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponse422) & {
  headers: Headers;
};

export type apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponse = (apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponseSuccess | apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponseError)

export const getApiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostUrl = (name: string,
    noteId: string,
    sha: string,) => {




  return `/api/workspaces/${name}/notes/${noteId}/history/${sha}/restore`
}

/**
 * @summary Api Restore Note Version
 */
export const apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePost = async (name: string,
    noteId: string,
    sha: string, options?: RequestInit): Promise<apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponse> => {

  const res = await fetch(getApiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostUrl(name,noteId,sha),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiRestoreNoteVersionApiWorkspacesNameNotesNoteIdHistoryShaRestorePostResponse
}
