import os
import sysconfig
import tempfile
from collections.abc import Callable, Iterator
from pathlib import Path

import pytest

# Some test modules import sqlalchemy before kajet_turbo, bypassing the guard
# in kajet_turbo/__init__.py — set it here too (conftest runs first), so the
# GIL stays disabled on free-threaded builds.
if sysconfig.get_config_var("Py_GIL_DISABLED"):
    os.environ.setdefault("DISABLE_SQLALCHEMY_CEXT_RUNTIME", "1")

# kajet_turbo.dependencies runs Database() and create_auth() at module level on import.
# Both need env vars set before test files are collected by pytest.
if "DB_PATH" not in os.environ:
    _db_fd, _db_path = tempfile.mkstemp(suffix=".db")
    os.close(_db_fd)  # SQLite reopens the (empty) file itself
    os.environ["DB_PATH"] = _db_path
if "MCP_BASE_URL" not in os.environ:
    os.environ["MCP_BASE_URL"] = "http://localhost:8000"


def pytest_configure(config):
    # pytest-xdist workers inherit DB_PATH from the controller process and would
    # all run alembic upgrade head on the same file simultaneously → race.
    # Override to a per-worker temp file before any test file is collected.
    worker_input = getattr(config, "workerinput", None)
    if worker_input is not None:
        worker_id = worker_input.get("workerid", "gw0")
        fd, path = tempfile.mkstemp(suffix=f"-{worker_id}.db")
        os.close(fd)
        os.environ["DB_PATH"] = path
        return

    # pytest's default basetemp (pytest-of-<user>/pytest-<N>, last-3 retention) is one
    # shared pool per OS user: independent pytest invocations from different worktrees
    # (or two runs of this suite started close together) race for numbered dirs and can
    # have a still-running run's tmp_path directory garbage-collected out from under it
    # (pytest-dev/pytest#7911, pytest-dev/py#30). mkdtemp sidesteps the shared pool
    # entirely — every invocation gets its own OS-guaranteed-unique directory, so two
    # worktrees (or two overlapping runs anywhere) never share one. Only the controller
    # sets this; xdist already nests worker basetemps under whatever the controller
    # picks, same as it does with the default. Skip if the caller passed --basetemp
    # explicitly — that is an intentional override we should not fight.
    if config.option.basetemp is None:
        config.option.basetemp = tempfile.mkdtemp(prefix="kajet-pytest-")


import shutil

from sqlmodel import Session

from kajet_turbo.db import Database
from kajet_turbo.models import User
from kajet_turbo.repositories.git import GitRepository
from kajet_turbo.workspace import NoteFrontmatter, note_filepath, write_note_file


def seed_user(database: Database, user_id: str) -> None:
    """Insert a User row with a fixed id — workspace_access/workspace_remotes/jobs FK to
    users.id, and several tests need a predictable id (e.g. "u1") rather than one
    generated by UserRepository.create. A no-op if the id already exists, so a file's own
    explicit seeding and an autouse fixture calling this for the same id don't collide."""
    with Session(database.engine) as session:
        if session.get(User, user_id) is not None:
            return
        session.add(
            User(
                id=user_id,
                email=f"{user_id}@test.com",
                password_hash="x",
                created_at="2026-01-01",
            )
        )
        session.commit()


@pytest.fixture(scope="session")
def _db_template(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Migrated DB created once per worker session; tests copy it instead of re-running Alembic."""
    path = tmp_path_factory.mktemp("db-template") / "template.db"
    db = Database(str(path))
    db.close()
    return path


@pytest.fixture
def database_factory(tmp_path: Path, _db_template: Path) -> Iterator[Callable[..., Database]]:
    databases: list[Database] = []

    def create(name: str = "test.db") -> Database:
        dest = tmp_path / name
        shutil.copy2(_db_template, dest)
        database = Database(str(dest), skip_migrations=True)
        databases.append(database)
        return database

    yield create

    for database in databases:
        database.close()


@pytest.fixture
def database(database_factory: Callable[..., Database]) -> Database:
    return database_factory()


@pytest.fixture
def git_workspace_factory(tmp_path: Path) -> Callable[[str], Path]:
    def create(relative_path: str = "workspace") -> Path:
        workspace = tmp_path / relative_path
        workspace.mkdir(parents=True, exist_ok=True)
        GitRepository.init(str(workspace))
        return workspace

    return create


@pytest.fixture
def note_file_factory() -> Callable[..., str]:
    def create(
        workspace: str | Path,
        title: str = "Test Note",
        *,
        note_id: str | None = "note-001",
        folder: str = "",
        tags: list[str] | None = None,
        content: str = "Test content",
        created_at: str = "2026-01-01T00:00:00+00:00",
        updated_at: str = "2026-01-01T00:00:00+00:00",
        extras: dict[str, object] | None = None,
    ) -> str:
        path = note_filepath(str(workspace), folder, title)
        meta = NoteFrontmatter(
            id=note_id,
            title=title,
            tags=tags or [],
            created_at=created_at,
            updated_at=updated_at,
            extras=extras or {},
        )
        write_note_file(path, meta, content)
        return path

    return create
