"""Pure, deterministic markdown processing built on the markdown-it-py token stream.

No I/O, no DB, no module-level mutable state — safe under free-threaded Python.
Public API is re-exported here; private helpers live in the submodules / `_parser` / `_tokens`.
"""

from kajet_turbo.markdown.chunking import (
    DEFAULT_HARD_MAX,
    Chunk,
    chunk_markdown,
    embedded_text,
)
from kajet_turbo.markdown.link_index import (
    AmbiguousLink,
    CaseCorrectedLink,
    LinkIndex,
    LinkMatch,
    LinkResolution,
    join_target,
    resolve_content_links,
    split_target,
)
from kajet_turbo.markdown.note_edit import (
    AnchorAmbiguousError,
    AnchorNotFoundError,
    EditMode,
    EditResult,
    EditSpec,
    HeadingAmbiguousError,
    HeadingNotFoundError,
    Section,
    append_content,
    apply_edit,
    find_section_by_heading,
    insert_after,
    parse_sections,
    prepend_content,
    replace_section,
    replace_text,
)
from kajet_turbo.markdown.outline import OutlineSection, build_outline
from kajet_turbo.markdown.tags import (
    ancestors,
    extract_inline_tags,
    normalize,
    remap_path,
    rewrite_inline_tags,
    segments,
)
from kajet_turbo.markdown.wikilinks import (
    BrokenWikilinkError,
    IndexedNote,
    LinkResolver,
    XwsResolver,
    extract_wikilinks,
    note_explorer_url,
    render_markdown,
    rewrite_wikilinks,
)

__all__ = [
    "DEFAULT_HARD_MAX",
    "AmbiguousLink",
    "AnchorAmbiguousError",
    "AnchorNotFoundError",
    "BrokenWikilinkError",
    "CaseCorrectedLink",
    "Chunk",
    "EditMode",
    "EditResult",
    "EditSpec",
    "HeadingAmbiguousError",
    "HeadingNotFoundError",
    "IndexedNote",
    "LinkIndex",
    "LinkMatch",
    "LinkResolution",
    "LinkResolver",
    "OutlineSection",
    "Section",
    "XwsResolver",
    "ancestors",
    "append_content",
    "apply_edit",
    "build_outline",
    "chunk_markdown",
    "embedded_text",
    "extract_inline_tags",
    "extract_wikilinks",
    "find_section_by_heading",
    "insert_after",
    "join_target",
    "normalize",
    "note_explorer_url",
    "parse_sections",
    "prepend_content",
    "remap_path",
    "render_markdown",
    "replace_section",
    "replace_text",
    "resolve_content_links",
    "rewrite_inline_tags",
    "rewrite_wikilinks",
    "segments",
    "split_target",
]
