"""note_chunks index_meta and note index_state

Revision ID: 313b4b5a2917
Revises: 5fffaf57055c
Create Date: 2026-06-21 11:49:57.528035

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "313b4b5a2917"
down_revision: str | Sequence[str] | None = "5fffaf57055c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_meta",
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("backend", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "note_chunks",
        sa.Column("chunk_rowid", sa.Integer(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("note_id", sa.Text(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("header_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes.id"],
        ),
        sa.PrimaryKeyConstraint("chunk_rowid"),
    )
    with op.batch_alter_table("note_chunks", schema=None) as batch_op:
        batch_op.create_index("ix_note_chunks_note", ["note_id"], unique=False)

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "index_state",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="stale",
            )
        )
        batch_op.add_column(
            sa.Column("indexed_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###
    op.execute("DROP TABLE IF EXISTS notes_vec")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_column("indexed_at")
        batch_op.drop_column("index_state")

    with op.batch_alter_table("note_chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_note_chunks_note")

    op.drop_table("note_chunks")
    op.drop_table("index_meta")
    # ### end Alembic commands ###
