"""chunk-level notes_fts and drop fts_rowid

Revision ID: 3b7429883579
Revises: 313b4b5a2917
Create Date: 2026-06-21 13:01:08.170528

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b7429883579"
down_revision: str | Sequence[str] | None = "313b4b5a2917"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop the note-level FTS table so existing DBs rebuild it at chunk level
    # via Database._init_schema (CREATE VIRTUAL TABLE IF NOT EXISTS).
    op.execute("DROP TABLE IF EXISTS notes_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_column("fts_rowid")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fts_rowid", sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
