"""embedding_profiles replaces user_embedding_config

Revision ID: ace088fd628e
Revises: 3b7429883579
Create Date: 2026-06-21 16:31:03.831268

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ace088fd628e"
down_revision: str | Sequence[str] | None = "3b7429883579"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_profiles",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key_enc", sa.LargeBinary(), nullable=True),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("embedding_profiles", schema=None) as batch_op:
        batch_op.create_index("ix_embedding_profiles_user", ["user_id"], unique=False)

    op.drop_table("user_embedding_config")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_embedding_config",
        sa.Column("user_id", sa.TEXT(), nullable=False),
        sa.Column("backend_id", sa.TEXT(), nullable=True),
        sa.Column("api_key_enc", sa.BLOB(), nullable=True),
        sa.Column("created_at", sa.VARCHAR(), nullable=False),
        sa.Column("updated_at", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("embedding_profiles", schema=None) as batch_op:
        batch_op.drop_index("ix_embedding_profiles_user")

    op.drop_table("embedding_profiles")
    # ### end Alembic commands ###
