"""add note_links

Revision ID: f8250264e0ee
Revises: df05be5ced90
Create Date: 2026-06-13 11:11:10.463214

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8250264e0ee"
down_revision: str | Sequence[str] | None = "df05be5ced90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note_links",
        sa.Column("source_note_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_note_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("source_note_id", "target_note_id"),
    )
    with op.batch_alter_table("note_links", schema=None) as batch_op:
        batch_op.create_index(
            "ix_note_links_target", ["target_note_id", "source_note_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("note_links", schema=None) as batch_op:
        batch_op.drop_index("ix_note_links_target")

    op.drop_table("note_links")
    # ### end Alembic commands ###
