from enum import StrEnum


class NoteError(StrEnum):
    NOT_FOUND = "NOTE_NOT_FOUND"
    ALREADY_EXISTS = "NOTE_ALREADY_EXISTS"
    TITLE_REQUIRED = "NOTE_TITLE_REQUIRED"
    BROKEN_WIKILINK = "BROKEN_WIKILINK"
    INVALID_INPUT = "NOTE_INVALID_INPUT"
