from enum import StrEnum


class SshKeyError(StrEnum):
    NAME_REQUIRED = "SSH_KEY_NAME_REQUIRED"
    NAME_TAKEN = "SSH_KEY_NAME_TAKEN"
    INVALID_ALGORITHM = "SSH_KEY_INVALID_ALGORITHM"
    NOT_FOUND = "SSH_KEY_NOT_FOUND"
