from enum import StrEnum


class TargetError(StrEnum):
    NOT_FOUND = "TARGET_NOT_FOUND"
    ACCESS_DENIED = "TARGET_ACCESS_DENIED"
    INVALID_INPUT = "TARGET_INVALID_INPUT"
    MIXED_WORKSPACES = "TARGET_MIXED_WORKSPACES"
