from enum import StrEnum


class WorkspaceError(StrEnum):
    NOT_FOUND = "WORKSPACE_NOT_FOUND"
    ALREADY_EXISTS = "WORKSPACE_ALREADY_EXISTS"
    NAME_REQUIRED = "WORKSPACE_NAME_REQUIRED"
    INVALID_INPUT = "WORKSPACE_INVALID_INPUT"
