from enum import StrEnum


class WorkspaceRemoteError(StrEnum):
    NOT_FOUND = "WORKSPACE_REMOTE_NOT_FOUND"
    NOT_CONFIGURED = "WORKSPACE_REMOTE_NOT_CONFIGURED"
    INVALID_INPUT = "WORKSPACE_REMOTE_INVALID_INPUT"
